### ISSUE TITLE
Provide <Plug> mappings for vim legacy users

### ISSUE THREAD

**Issue by saccarosium** [girishji/scope.vim#11]
I use vim 9 but with a legacy vimrc, for compatibility reasons, and I'm not really hable to use this plugin (at least that I know of).

If you don't know what <Plug> mappings are checkout `:h <Plug>` and `:h using-<Plug>`.

**Comment by girishji** [comment]
Can you try `fuzzy#File()` instead? It should autoload.

**Comment by ttkap** [comment]
try something like:
```
nnoremap <yourkey> <scriptcmd>vim9cmd scope#fuzzy#Keymap()<CR>
```

**Comment by girishji** [comment]
Maybe `<plug>` is still better if it goes looking for `scope/fuzzy.vim` in `autoload` directories available in `VIMRELTIME` every time key is invoked. I don't know how legacy script works.

**Comment by girishji** [comment]
We want to allow user to pass arguments to functions. They may prefer `rg` with specific flags instead of the default `grep` in `fuzzy.Grep()`. In case of `find` I have multiple key mappings (to search Vim src files, my .vim dir, etc.). How to deal with that since `<Plug>` does not take arguments (if I remember correctly)?

**Comment by saccarosium** [comment]
> We want to allow user to pass arguments to functions.

I see... This is probably not for me than. But I would suggest to do two things.

Document how to use the plugin from legacy vimscript (at least the simple stuff like this `nnoremap <yourkey> <scriptcmd>vim9cmd scope#fuzzy#Keymap()<CR>`)

I think it is a better idea to provide the main functions in a "scope" below. `scope#Keymap()` rather than `scope#fuzzy#Keymap()`. You can achieve this by simply have a structure like this:

```
autoload/
| scope/ <- directory
| scope.vim <- file
```

Thanks for the support

**Comment by girishji** [comment]
Thanks for suggestions.

**Comment by girishji** [comment]
I think creating a bunch of commands (that can also be key-mapped) may work out better for legacy script users. Commands can take arguments, and can have custom completion.

**Comment by saccarosium** [comment]
>Also, I think putting scope.vim directly inside autoload will create conflict if user has >.vim/autoload/scope.vim, and decides to do import autoload 'scope.vim'. In legacy script >function names can be qualified with # like function scope#Keymap(), but it does not work for def in vim9script.

After some testing here is what I found.

>```
>autoload/
>| scope/ <- directory
>| scope.vim <- file
>```

If you do this and the user has a script named scope in their autoload dir the plugin will be shadowed. So yea this is not a good idea. I've mentioned it because it is the pattern used in legacy plugins. I guess this is not applicable anymore.

> I think creating a bunch of commands (that can also be key-mapped) may work out better for legacy script users. Commands can take arguments, and can have custom completion.

Yes, this is the way to go, in my opinion.

**Comment by girishji** [comment]
> If you do this and the user has a script named scope in their autoload dir the plugin will be shadowed.

This is expected since plugins are loaded first. Even though autoload is lazy loading, it actually gets the symbol names up front.

**Comment by girishji** [comment]
Added the commands, see README. `:Scope <tab>`.
