### ISSUE TITLE
LSP client not found

### ISSUE THREAD

**Issue by aauren** [girishji/scope.vim#13]
Whenever I try to launch scope.vim from a key binding (`nnoremap <C-p> <scriptcmd>vim9cmd scope#fuzzy#File()<CR>`)I get the following error and no modal dialog appears

```
Error detected while processing /home/<home>/.vim/bundle/scope.vim/autoload/scope/fuzzy.vim[6]../home/auren/.vim/bundle/scope.vim/autoload/scope/lsp.vim:
line    4:
LSP client not found
```

This appears to come from 

```
if !exists('g:loaded_lsp')
    echoerr 'LSP client not found'
    finish
endif
```

But I can't see anything that sets `g:loaded_lsp`. I did notice from the readme a link to https://github.com/yegappan/lsp so maybe it comes from there? However, I don't see in the requirements section that this is something that is required.

Additionally, I already use `coc.vim` for this purpose and would prefer not to use https://github.com/yegappan/lsp if at all possible.

**Comment by aauren** [comment]
FWIW Subsequent key combos after the error all appear to work.

**Comment by girishji** [comment]
Should be fixed.

**Comment by aauren** [comment]
I can confirm that after updating this is fixed.

Quick question before I close this out, what was the expected functionality that I was missing by not having `g:loaded_lsp` set?

**Comment by girishji** [comment]
`LspDocumentSymbols()`. It gathers symbols from LSP and you can search on them and jump. But it does not work yet since there is a PR that needs to be merged to yegappan lsp.

**Comment by aauren** [comment]
Is there any chance that you will support other LSP integrations like coc.vim in the future?

**Comment by girishji** [comment]
I updated the comment. LspDocumentSymbols() should work.

Other LSP clients can be supported only if their APIs are exported. I use yegappan lsp, so it is no 'extra work' for me to look into issues. I can also make changes to yegappan lsp since I know the codebase quite well. Other Lsp's are extra work only because I do not know the codebase and it is not pleasant wading through legacy script (unlike vim9script).

**Comment by aauren** [comment]
Thanks for all your help! And for putting this plugin together!

I had been looking for how to get grep-like functionality from CTRLP for a long time. This plugin is a hugely forward for me!
