### ISSUE TITLE
Can't paste word in socpe win inputline

### ISSUE THREAD

**Issue by Angluca** [girishji/scope.vim#15]
I press ```<c-v>``` display ```"+gP```, can't paste my copy word
Must press ```<c-r>+``` if want paste success

**Comment by girishji** [comment]
Maybe because `<C-v>` is mapped to split the window vertically. Can you do `:Scope command` and see if you can paste?

**Comment by girishji** [comment]
In terminal Vim, can you paste into buffer in insert-mode (without popup window)? Maybe clipboard encoding is incorrect.

**Comment by girishji** [comment]
For terminal vim you have to disable bracketed paste:

```
&t_BE = ""
&t_BD = "\e[?2004l"
exec "set t_PS=\e[200~"
exec "set t_PE=\e[201~"
```

**Comment by girishji** [comment]
macvim does NOT work for me also :( 
I get the same "+gP
most likely a bug specific to macvim.
