### ISSUE TITLE
Copy text from outside in search field work not correct  

### ISSUE THREAD

**Issue by greeschenko** [girishji/scope.vim#16]
Hello, if I try to copy text from clipboard to search field I see extra characters

![20240326-180131_1920x1080](https://github.com/girishji/scope.vim/assets/2754533/cfab37c4-b9fd-47ec-90fd-d0371e76729c)

**Comment by girishji** [comment]
I already added a note to README. Disable bracketed paste:
```
&t_BE = ""
&t_BD = "\e[?2004l"
exec "set t_PS=\e[200~"
exec "set t_PE=\e[201~"
```
