### ISSUE TITLE
How to limit height of popup window?

### ISSUE THREAD

**Issue by airblade** [girishji/scope.vim#17]
First of all, thank you for writing this plugin.  It is really fast and I appreciate not having external dependencies.

I would like to limit the height of the popup window so that only the best, say, 10 results are shown.  I have two reasons:

- It's overwhelming to try to comprehend a screenful of results.
- Speed: less redrawing is required when the popup window is smaller.

I tried this but it didn't make any difference:

```vim
call scope#popup#OptionsSet({
  maxheight: 10
})
```

Thanks!

**Comment by girishji** [comment]
Try now, it should work.
