### ISSUE TITLE
FindCmdExcludeDirs and default

### ISSUE THREAD

**Issue by DanielViberg** [girishji/scope.vim#18]
Is FindCmdExcludeDirs used? 

When i search for files using find it includes files in directories listed in my .gitignore and makes it slow.

**Comment by girishji** [comment]
It's not used. It excludes paths present in .ignore and .config/fd/ignore. You can try it if it suits you. 
```
fuzzy.Find(util. FindCmdExcludeDirs(), ...)
```
Maybe it is better to just exclude .ignore paths by default.

**Comment by DanielViberg** [comment]
I guess it depends on what the focus is for the user, I primarly use vim as IDE in large codebases, but some might not. I would prefer it as default, but its up to you.

**Comment by DanielViberg** [comment]
Maybe an ability to configure it on or off would suffice?
