### ISSUE TITLE
respect wildignore

### ISSUE THREAD

**Issue by dacyberduck** [girishji/scope.vim#20]
Is it possible for Find & Grep functions to respect vim's wildignore option?

**Comment by girishji** [comment]
Try now.

**Comment by dacyberduck** [comment]
https://github.com/girishji/scope.vim/commit/fb7ef005048c674445af1b942e9fbd122d2264ca#r141067126

**Comment by dacyberduck** [comment]
> Try now.

Since it working on your end, should I close this issue? I am assuming I have to find the right `grep` format myself since these commands differ from system to system.

**Comment by girishji** [comment]
BSD and Linux greps work different. See comment in the diff file. It should work for you now.

**Comment by girishji** [comment]
Also, it now automatically excludes `.git` from both Find and Grep. I think it is a good default behavior to have.
