### ISSUE TITLE
How to scope grep to specific directory?

### ISSUE THREAD

**Issue by airblade** [girishji/scope.vim#22]
I often want to grep within a certain directory.  I know I can specify the directory as the last argument to the `Grep` function – but I'm not sure how to do that dynamically.

If I were to do it statically, I could set up different maps where I know the specific directory up front.  For example (legacy syntax):

```vim
nnoremap <leader>ga <scriptcmd> scope#fuzzy#Grep('rg --vimgrep --no-heading --smart-case', v:true, '<cword>', 'app/')
nnoremap <leader>gc <scriptcmd> scope#fuzzy#Grep('rg --vimgrep --no-heading --smart-case', v:true, '<cword>', 'config/')
nnoremap <leader>gd <scriptcmd> scope#fuzzy#Grep('rg --vimgrep --no-heading --smart-case', v:true, '<cword>', 'db/')
```

But that clogs up my maps a bit and having to specify the directories ahead of time is not ideal.

Is there a nice way to take the directory from the user input?  For example if the first or last input word ends in `/`, use that as the directory.

I imagine you wouldn't want to change the `Grep` function itself because then there would need to be a way to escape `app/` if you wanted to search for that literal string, so perhaps there's a way to write a wrapper function that has the directory-extraction logic and then forwards the rest of the input to `Grep`.  Does anything come to mind?

Thank you!  I really like using this plugin.

**Comment by girishji** [comment]
You can use the Vim command. See README:

`Grep` takes additional arguments. `:Scope {Grep|grep} [dir] [str]` starts a live search with 'str' as the initial search string if non-empty. If 'dir' is specified, search in that directory instead of the current directory.

**Comment by girishji** [comment]
Oh, wait, you want to use `rg` instead. Just define your own Vim command. See command.vim and plugin/scope.vim

```
def DoGrep(...)
    fuzzy.Grep(...)
enddef
command -nargs=+  ScopeGrep DoGrep(<f-args>)
```

**Comment by airblade** [comment]
Thanks for the suggestions!  Sadly I haven't managed to make it work yet.  This is what I have so far:

```vim
function! DoGrep(...)
  echom a:000
  if a:0 == 1
    let dir = '.'
  else
    let dir = a:000[-1]
  endif
  let needle = join(a:000[:-2], ' ')
  call scope#fuzzy#Grep('rg --vimgrep --no-heading --smart-case', v:true, '', dir)
endfunction

command! -nargs=+ ScopeGrep call DoGrep(<f-args>)
```

Where you invoke it like this: `:ScopeGrep foo app/`.  However it doesn't work at all :/  I can't see how to pass `needle` into the `Grep` function, the way you would with `:Scope {Grep|grep} [dir] [str]`.

---

I'd like to be able to invoke the grep feature with a keystroke, and when it pops up the window, type my search pattern followed by the directory into the input area – the same way you would if invoking `rg` on the command line.  

When I try it with the out-of-the-box API via the following map...

```vim
nnoremap <leader>g <scriptcmd>vim9cmd scope#fuzzy#Grep('rg --vimgrep --no-heading --smart-case', v:true, '<cword>')<CR>
```

...and I type into the popup...

<img width="204" alt="Screenshot 2024-04-19 at 10 31 30 am" src="https://github.com/girishji/scope.vim/assets/7265/9ccd259b-45b3-4118-9d73-a5e14758b6bf">

...the command echoed is:

```
rg --vimgrep --no-heading --smart-case user\ app/ ./
```

It's almost what I'd like.  If the space between `user` and `app` weren't escaped, and the [`./` weren't automatically appended](https://github.com/girishji/scope.vim/blob/e0e0a6b92448c6c5d6ee75d369b8bec0bb288840/autoload/scope/fuzzy.vim#L128-L129), it would be perfect.

**Comment by girishji** [comment]
I see. Wait for my next commit.

**Comment by girishji** [comment]
Please see the diff in README for usage. I gave several examples. For your use case try :

```
command -nargs=1 -complete=dir ScopeGrep fuzzy.Grep('rg --vimgrep', true, null_string, <f-args>)
nnoremap <yourkey> :ScopeGrep<space>

```

You have to enter the dirname once before it starts live grep. The design you proposed above will not work well with this plugin, since every space is escaped (so you can search multiple words). If you pass dirname as the last word, it will just be treated as part of the pattern to search. In the API, the last argument is the dirname, which is used in the above command.

**Comment by airblade** [comment]
That works perfectly.  Thank you very much!
