### ISSUE TITLE
Feature: Execute `File()` Search From git Root

### ISSUE THREAD

**Issue by aauren** [girishji/scope.vim#26]
One of the features that I liked a lot from CTRL-P was that when I was within a git source repo, it would automatically execute `File()` searches from the top of the git source root, even if I had opened vim from within a sub-directory of that root.

Would it be possible to have scope.vim do something similar?

**Comment by girishji** [comment]
This is already possible, but I added clear examples. For your use case you can add the following keymap:

```
nnoremap <your_key> <scriptcmd>fuzzy.File(fuzzy.FindCmd($'{system("git rev-parse --show-toplevel 2>/dev/null \|\| true")->trim()}'))<cr>

```

**Comment by aauren** [comment]
@girishji - Thanks for the response. I think what you said makes sense, but I'm struggling a bit because I have all of my mappings currently in VIM legacy format.

I went ahead and defined the `FindGit()` from your comment in vim9. Do you have any idea how to call that from a mapping that is being made in a legacy vim config file? I've been going through the docs, but I can't find any shortcuts to understanding how to do this.

As a fallback, I guess I can make the mapping in vim9 as well, but I was trying to keep all of my mappings in one place for now.

**Comment by girishji** [comment]
Can you try:

```
nnoremap <your_key> <scriptcmd>vim9cmd scope#fuzzy#File(scope#fuzzy#FindCmd($'{system("git rev-parse --show-toplevel 2>/dev/null \|\| true")->trim()}'))<cr>
```

This is explained in README.

If you like own legacy script function:

```
    function s:FindGit()
        let gitdir = system("git rev-parse --show-toplevel 2>/dev/null")->trim()
        if v:shell_error != 0 || gitdir == getcwd()
            let gitdir = '.'
        endif
        call scope#fuzzy#File(scope#fuzzy#FindCmd(gitdir))
    endfunction
    nnoremap <expr> <your_key> <SID>FindGit()

```

**Comment by aauren** [comment]
Thanks @girishji!

I think that I'm getting closer. I was originally getting an error saying that it couldn't find `FindCmd`, but then I realized, that's because you made a recent update that added that to the `fuzzy` scope from the `utils` scope.

Since I made that update though, I now get the following error which is different from this I believe:

```
E488: Trailing characters: ^M
Press ENTER or type command to continue
Error detected while processing function <lambda>20[1]..<lambda>17[15]..FilterMenu.SetText[10]..FilterMenu._SetPopupContent:
line    8:
E523: Not allowed here
```

I have tried getting rid of pretty much the entire function except for:

```
    function s:FindGit()
        call scope#fuzzy#File()
    endfunction
```

And I still get this error. Do you have any idea where this is coming from?

**Comment by girishji** [comment]
Nothing stands out. Can you start from empty `.vimrc` and put the above keymap and see if it works. Then slowly add other things you have and see when it stops working.

**Comment by aauren** [comment]
Thanks for all of your help with this @girishji!

I really appreciate your patience with me and your willingness to write such a cool plugin.

At the end of the day I ran out of time, and decided to just use vim9 script for my key bindings instead of trying to shim it into legacy vim script.

For what its worth, I ended up with the following `FindGit()` function in vim9 script because I didn't like how the directories expanded out with the first iteration of `FindGit()` (e.g. I wanted to change them from full paths to relative paths):

```vim
  def FindGit()
      # Suppress error from 'git' command and always return success so that 'system()' is happy
      var full_gitdir = system("git rev-parse --show-toplevel 2>/dev/null \|\| true")->trim()
      var rel_gitdir = system("realpath --relative-to=" .. shellescape(getcwd()) .. " " .. full_gitdir .. " 2>/dev/null \|\| true")->trim()
      fuzzy.File(fuzzy.FindCmd(rel_gitdir))
  enddef
```

**Comment by girishji** [comment]
Looks good. You can shorten it as:
```
var rel_gitdir = system($"realpath --relative-to={shellescape(getcwd())} {full_gitdir} 2>/dev/null \|\| true")->trim()

 ```
