### ISSUE TITLE
Error in grepcmd

### ISSUE THREAD

**Issue by pedrohgmacedo** [girishji/scope.vim#28]
I defined:
```vim
nn <silent> <leader>fg <scriptcmd>vim9cmd scope#fuzzy#Grep('rg --vimgrep --smart-case', 1, '', '/path/to/foo')<cr>
```

Typed `aaa ` And got these errors:
```
rg --vimgrep --smart-case a /path/to/foo

rg --vimgrep --smart-case aa /path/to/foo

rg --vimgrep --smart-case aaa /path/to/foo

rg --vimgrep --smart-case aaa\  /path/to/foo
Error detected while processing function <lambda>22:
line    2:
error: rg: regex parse error: from rg --vimgrep --smart-case aaa\  /path/to/foo
error:     (?:aaa\) from rg --vimgrep --smart-case aaa\  /path/to/foo
error:     ^ from rg --vimgrep --smart-case aaa\  /path/to/foo
error: error: unclosed group from rg --vimgrep --smart-case aaa\  /path/to/foo
```

**Comment by girishji** [comment]
I could not reproduce. You may have older version. But I found issue with escaping `)` that shows up in `rg` only, and it is fixed. Pl upgrade.

**Comment by pedrohgmacedo** [comment]
I was on the latest commit. For reference, &shellxescape on windows is set to "&|<>()@^ by standard.

**Comment by girishji** [comment]
I do not have windows. It looks like escape character should be `^` but I am using `\`. Can you set `grep_echo_cmd` option and check what it is sending to the shell? It prints the command string in the commandline.

Can you run your `rg ...` command on the shell, using proper escape char for all the characters listed in `:set shellxescape?` and see if it works? And then I can modify this plugin to use appropriate escape for windows.


```
						*'shellxescape'* *'sxe'*
'shellxescape' 'sxe'	string	(default: "";
				 for MS-Windows: "\"&|<>()@^")
			global
	When 'shellxquote' is set to "(" then the characters listed in this
	option will be escaped with a '^' character.  This makes it possible
	to execute most external commands with cmd.exe.
	This option cannot be set from a |modeline| or in the |sandbox|, for
	security reasons.

						*'shellxquote'* *'sxq'*
'shellxquote' 'sxq'	string	(default: "";
					for Win32, when 'shell' is cmd.exe: "("
					for Win32, when 'shell' is
					powershell.exe: "\""
					for Win32, when 'shell' contains "sh"
					somewhere: "\""
					for Unix, when using system(): "\"")
			global
	Quoting character(s), put around the command passed to the shell, for
	the "!" and ":!" commands.  Includes the redirection.  See
	'shellquote' to exclude the redirection.  It's probably not useful
	to set both options.
	When the value is '(' then ')' is appended. When the value is '"('
	then ')"' is appended.
	When the value is '(' then also see 'shellxescape'.
	This is an empty string by default on most systems, but is known to be
	useful for on Win32 version, either for cmd.exe, powershell.exe, or
	pwsh.exe which automatically strips off the first and last quote on a
	command, or 3rd-party shells such as the MKS Korn Shell or bash, where
	it should be "\"".  The default is adjusted according the value of
	'shell', to reduce the need to set this option by the user.  See
	|dos-shell|.
	This option cannot be set from a |modeline| or in the |sandbox|, for
	security reasons.
```

**Comment by pedrohgmacedo** [comment]
> rg --vimgrep --smart-case a /path/to/foo
> 
> rg --vimgrep --smart-case aa /path/to/foo
> 
> rg --vimgrep --smart-case aaa /path/to/foo

I believe redir was done with grep_echo_cmd on.

**Comment by pedrohgmacedo** [comment]
FYI, I'm not sure I understood your request, by when I call 
```vim
:shellscape('rg --vimgrep --smart-case a /path/to/foo \ " & | < > ( ) @ ^')
```
I get
```
"rg --vimgrep --smart-case a /path/to/foo \ "" & | < > ( ) @ ^"
```

**Comment by girishji** [comment]
Try :
```
C:\Users\pedro> rg --vimgrep --smart-case a\  /path/to/foo
```
and see if it gives the correct results. Then try other escaped characters like `& | ( ) ` etc. instead of `\`.

If you are not getting correct results running `rg` directly in shell, try escaping `\` with `^` or `(` and `)' around. Read the doc I posted above.

Maybe:
```
C:\Users\pedro> rg --vimgrep --smart-case a^\  /path/to/foo
```
or:
```
C:\Users\pedro> rg --vimgrep --smart-case a\\\  /path/to/foo
```
you have to experiment what works.

**Comment by pedrohgmacedo** [comment]
`rg --vimgrep --smart-case "a "  /path/to/foo `

is the only one that worked.

**Comment by girishji** [comment]
What do you get in Vim when you do `:set sxe?` and `:set sxq?`

**Comment by girishji** [comment]
Try now, and see if it improves.

**Comment by pedrohgmacedo** [comment]
> Try now, and see if it improves.

It works now, thanks!

**Comment by pedrohgmacedo** [comment]
> What do you get in Vim when you do `:set sxe?` and `:set sxq?`

Honestly, I think it would be better to just check 'has('win64')'

**Comment by pedrohgmacedo** [comment]
> Will about powershell?

Precisely because of powershell lol, it also only works using quotes.
