### ISSUE TITLE
MRU (OldFiles) probably mutates v:oldfiles

### ISSUE THREAD

**Issue by EgZvor** [girishji/scope.vim#3]
After running the MRU function once, the second time it's not working

```vim
Error detected while processing function scope#fuzzy#MRU[7]..<lambda>19:                                                                                                                                                               
line    1:
E1013: Argument 1: type mismatch, expected string but got dict<string>
```

I suspect it's because `:h filter()` and `:h map()` here https://github.com/girishji/scope.vim/blob/17dec07712708dbe965b670e8ee28b71257d3e47/autoload/scope/fuzzy.vim#L290 mutate the argument v:oldfiles and then all hell breaks loose.

**Comment by EgZvor** [comment]
Yes, adding a `copy()` fixes it.

**Comment by girishji** [comment]
That's clearly a bug. filter() modifies in place. Bram provided mapnew() but not filternew(). 
https://github.com/girishji/scope.vim/commit/19a84394fc04d1743cdc6a5b15dec73d64be3ff4 fix this.
