### ISSUE TITLE
Prompt window  and main window are not correctly aligned when using maxwidth settings

### ISSUE THREAD

**Issue by gcanat** [girishji/scope.vim#30]
When using maxwidth option, the prompt window is not aligned.

![scope](https://github.com/girishji/scope.vim/assets/72149218/fcee666b-aabe-4109-8d8e-53bdf2281c3d)

As soon as we  filter out enough  items and the scrollbar is gone,  the prompt  window is aligned  with the  main window.

to reproduce:
```
import autoload 'scope/popup.vim' as sp
sp.OptionsSet({
  maxwidth: 140,
})
```

vim version: 9.1.429

**Comment by girishji** [comment]
Cannot reproduce. Are you using latest version of this plugin? What is the width of your terminal window? More info needed.

https://asciinema.org/connect/45e37ae2-dfce-4212-816a-85735b25fd7d

**Comment by gcanat** [comment]
I can reproduce with this minimal `vimrc` file
```
vim9script
import autoload 'scope/popup.vim' as sp
sp.OptionsSet({
  maxheight: 30,
  maxwidth: 80,
})
```
Oddly enough if I remove the maxheight  settings the issue disapears.

vim: version 9.1.426
os: ubuntu 22.04

**Comment by gcanat** [comment]
Yeah works. Thanks !
