### ISSUE TITLE
:Scope Find not ignore files from .gitignore

### ISSUE THREAD

**Issue by greeschenko** [girishji/scope.vim#31]
Hello after pull the changes ignoring from .gitignore does not work anymore 

![Screenshot from 2024-06-11 14-23-31](https://github.com/girishji/scope.vim/assets/2754533/315f5c86-65fa-4063-8085-1f72c70ee136)

try call :Scope Find and see all files except files from .git

![Screenshot from 2024-06-11 14-24-15](https://github.com/girishji/scope.vim/assets/2754533/82339604-b570-4453-8963-4d3255dd4d82)

**Comment by girishji** [comment]
It works for me. Can you set `find_echo_cmd` to `true` and check what command string it prints in the message area?

**Comment by greeschenko** [comment]
find echo already on screenshot
![Screenshot from 2024-06-11 14-24-15](https://github.com/girishji/scope.vim/assets/2754533/6a67c02b-e3c6-4ea3-a312-21f81f8d7c44)
and yes .gitignore is in the root directory

**Comment by girishji** [comment]
`././client/` is not correct. I think you do not have latest version. Can you upgrade this plugin?

**Comment by greeschenko** [comment]
Thank you, it was wrong .gitignore file in root
