### ISSUE TITLE
Cannot use Cmd+V to paste in Scope in MacVim

### ISSUE THREAD

**Issue by pusewicz** [girishji/scope.vim#32]
When opening Scope and trying to paste from the Clipboard, what is inserted is `"+gP` rather than the contents.

<img width="250" alt="image" src="https://github.com/user-attachments/assets/8d79a5f5-1e26-4176-9317-72c6edb6023c">

This only happens in MacVim.

Mappings: https://github.com/macvim-dev/macvim/blob/master/runtime/doc/os_mac.txt#L86

**Comment by pusewicz** [comment]
@girishji I have clipboard set to `unnamed`.

**Comment by girishji** [comment]
Please try the new version. I could not test it since MacVim had issues with installing Scope plugin with vim-plug. If you encounter issues pl. paste the error

**Comment by pusewicz** [comment]
@girishji It does paste, but still gets prepended with `"+g`. So if I have the word `vim` in my clipboard, when I paste, I see `"+gvim`. Then subsequent pastes en up pasing `"+gP` again:

<img width="240" alt="image" src="https://github.com/user-attachments/assets/24afdc1b-c8bc-4b05-b941-5d648ff18714">

**Comment by girishji** [comment]
Please try now.

**Comment by girishji** [comment]
Please test by pasting multiple times, and also in the middle of a typed string (not just the end).

**Comment by pusewicz** [comment]
This is now fixed!

**Comment by pusewicz** [comment]
@girishji How can I send you some money? Do you have GitHub sponsors set-up?

**Comment by girishji** [comment]
Thank you for your support! I just setup a Github sponsors page (https://github.com/sponsors/girishji), but waiting for their approval. If they approve tomorrow you'll be able to send money.
