### ISSUE TITLE
Few feature requests

### ISSUE THREAD

**Issue by ubaldot** [girishji/scope.vim#35]
Few feature requests:

~~1. Possibility to keep the same highlight in the displayed results. At the moment folders names are displayed with an _italic_ highlight which make my eyes tired.~~

EDIT: found:
```
  highlight default link ScopeMenuMatch Normal
  highlight default link ScopeMenuSubtle Normal
```

2. `:Scope File` takes into account of current folder, whereas `:Scope MRU` does not. For example if `pwd = ~/foo`, then `~/foo/bar.txt` is displayed as `bar.txt` in `:Scope File` and as `~/foo/bar.txt` in :`Scope MRU`. It is a matter of personal preferences, but I prefer to always get filenames displayed in terms of relative path. Perhaps user should be able to select that. 
~~3. The update rate is too fast sometimes and that leads to a sloppy experience when typing text. If I am not wrong it is about 100 ms. Would that be possible to either increase it or to leave the user to choose a custom value?~~
3.  When typing text in the search box the whole popup blinks at every keystroke. That is a bit disturbing. This is very evident in `:Scope Grep` Would that be possible to fix it?
EDIT: I tried to play around with `grep_poll_interval `and `timer_delay `(I increased both their value) but the problem is still there.

**Comment by girishji** [comment]
#2 
It is possible to add the feature you are requesting, but it may confuse people used to associating MRU list with the output of `v:oldfiles`, which lists the full path. Maybe I can add an option to toggle it.

#3 
You can set `grep_skip_len` to 2. Every time you type a character, it performs a grep and redraws the popup. It also has to redraw as more results appear (so increasing `grep_poll_interval` and  decreasing `grep_throttle_len` helps). Bram indicated somewhere that there is no way to avoid the blinking when it redraws, if I remember correctly.

**Comment by girishji** [comment]
2 )
I tested with `fnamemodify()` with `:.` and `:p:.` modifiers, but it does not work as you'd expect. The relative path is provided only 'if possible', meaning it will not insert '../' if necessary. You can suggest any other solution. Currently that feature is not possible.

**Comment by girishji** [comment]
Pl. reopen this if there is something more that needs to be done.

**Comment by ubaldot** [comment]
> You can set `grep_skip_len` to 2. Every time you type a character, it performs a grep and redraws the popup.

Do you need to redraw it necessarily? Isn't it possible to just use a `popup_settext()` to clean & rewrite new text?

**Comment by girishji** [comment]
`:redraw` is not called by the plugin though. I just checked carefully. When I do fuzzy.Grep() I do not see any blinking at every keystroke the way you described. Only the new text gets set in the popup window. I do not see anything weird. What is the problem exactly? Can you capture this in a video?

**Comment by ubaldot** [comment]
Here is a video: https://jmp.sh/s/a3VU1VzrQ6Wp9CZz4MM6

If the search time is smaller, then the blinking is even more annoying because the blinking frequency goes higher (blinking period is kinda of equal to the keystrokes time interval plus the search time).

**Comment by girishji** [comment]
Thanks for the video! I've never seen this behavior on mac or linux. Looks like `findstr` is not returning results fast enough. This is why you see blank screen so often. I'll look intothis.

**Comment by ubaldot** [comment]
Here is a video where I run the same command from powershell:

https://jmp.sh/s/BqATSVMlicOXTzbhbGMK

**Comment by ubaldot** [comment]
I may have made some local changes in the plugin, but I have no laptop right now. I will check later and let you know.

**Comment by ubaldot** [comment]
I re-installed the plugin and updated vim. 
Now it works fine. Thanks!

**Comment by ubaldot** [comment]
Tested with Grep. Here is the outcome: https://jmp.sh/s/1G8rb2ISLrlEeIE9P9Wj

**Comment by girishji** [comment]
You want it to pause searching until you finish typing the pattern 'validation'? You could use `:Scope grep <pattern>` (or bind `Scope grep<space>` to a key. After you search you can type `<c-k>` to enter fuzzy search mode where you can narrow the results of the search.

**Comment by ubaldot** [comment]
>You want it to pause searching until you finish typing the pattern 'validation'? You could use :Scope grep <pattern> (or bind >Scope grep<space> to a key. After you search you can type <c-k> to enter fuzzy search mode where you can narrow the results >of the search.

Neat solution thanks. Unrelated: no plans at all for adding preview windows in the plugin? At least with the grep, it would be handy.

**Comment by girishji** [comment]
I never thought of adding preview windows since I never use them. I am not even sure how much work is involved. I'm not sure I'd want to support something I myself don't use. Maybe you can fork this and try adding it.
