### ISSUE TITLE
Question: Is There a Way to Open All Filtered Items in Buffers?

### ISSUE THREAD

**Issue by aauren** [girishji/scope.vim#37]
Still love using scope.vim, and it has become a critical part of my everyday task. However, one of the features that I loved from ctrl-p was the ability to mark filtered items and then open them all as a set of buffers.

I could probably get away with not having the mark functionality, but being able to at the very least open all filtered items would be cool.

I'm aware that I can open them in a Location List or a QuickFix list, but as far as I can tell, VIM doesn't have an easy operation to open all of the items in a QuickFix / Location List either.

Any recommendations here? Or anything that might be able to be added to scope.vim?

**Comment by girishji** [comment]
Seems useful. try now.

**Comment by girishji** [comment]
`<C-o>` to send filtered files to buffer list, and `<C-g>` to send to arglist. arglist will be useful when you have lots of buffers open.

**Comment by aauren** [comment]
Thanks for the quick response! This is exactly what I was looking for, but I was hoping that it would apply more places. Specifically, I was trying to execute this on a Grep operation at the time when I submitted this issue.

Is it possible to make `<C-o>` and `<C-g>` apply to all scope.vim modal dialogs and not just the `File()` one? I tried transporting your code down to line #209 to see if I could work it out myself, but I don't think I have the Vim9 scripting chops for it.

**Comment by girishji** [comment]
Try it now pl.

**Comment by aauren** [comment]
Thanks again!

I think that its almost there. I found that I was still getting line numbers added to my buffers (e.g. `Makefile:1121`). I submitted https://github.com/girishji/scope.vim/pull/38 which makes the regex for the match on Grep operations just a little less greedy and more specific and this fixed up that last issue.

**Comment by aauren** [comment]
Thanks for all of your help! Its now working as expected!
