### ISSUE TITLE
Default configuration not working in linux

### ISSUE THREAD

**Issue by DanielViberg** [girishji/scope.vim#4]
Hello, thanks your vim 9 work!

Using the default configuration:
![image](https://github.com/girishji/scope.vim/assets/27137435/2f5244cb-3251-461f-8ac8-76890ed0ad15)

I get the following behavoiur.

![image](https://github.com/girishji/scope.vim/assets/27137435/c95a40f3-68f8-438e-8f3b-381dbc4f691e)

Pressing enter on the search.

![image](https://github.com/girishji/scope.vim/assets/27137435/1d3c67dd-3e47-48e3-9c6e-a246f584cf73)

**Comment by girishji** [comment]
You have set `grepprg` to  `grep -n $\* /dev/null`. This is incompatible, but in a way I did not foresee this. So I removed the dependence on grepprg. It should be fixed now.
https://github.com/girishji/scope.vim/commit/caa05c1c80030b86aabf64ab8d12acb90aaa5590 and https://github.com/girishji/scope.vim/commit/61b48a989c05477e2977c0f58e3114f70fce42fc
