### ISSUE TITLE
Error detected while processing function <lambda>84

### ISSUE THREAD

**Issue by DanielViberg** [girishji/scope.vim#8]
Hello, i'm getting an error in my laravel workspace:
```
Error detected while processing function <lambda>84:
line    2:
error: grep: public/storage: No such file or directory from grep --color=never -REIHin --exclude="*.git*" --exclude="*.swp" --exclude="*.zwc" --exclude-dir=plugged setPm
error: grep: public/storage: No such file or directory from grep --color=never -REIHin --exclude="*.git*" --exclude="*.swp" --exclude="*.zwc" --exclude-dir=plugged setPm
Press ENTER or type command to continue
```
VIM - Vi IMproved 9.1 (2024 Jan 02, compiled Mar 13 2024 08:11:41)
Included patches: 1-173
Linux itr1 6.5.0-25-generic #25~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Feb 20 16:09:15 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

**Comment by DanielViberg** [comment]
Suggestive solution is to add s to -RESIHin to -RESIHins to suppress errors

**Comment by girishji** [comment]
This is specific to ubuntu?

**Comment by girishji** [comment]
I think you have older version. We removed `-S` already.

**Comment by DanielViberg** [comment]
Could be:
grep (GNU grep) 3.7
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

**Comment by girishji** [comment]
https://www.gnu.org/software/grep/manual/grep.html#index-_002ds does not have -S, so I we removed it. Now it cannot follow symlinks. But maybe -Ss maybe better.

**Comment by girishji** [comment]
fixed by https://github.com/girishji/scope.vim/pull/5

**Comment by DanielViberg** [comment]
I believe the -s and -S have different purposes, to my understanding, -s is meant for suppressing errors -S something else. My suggestion here is to add -s as default to not report errors. And not to add -S again, as detailed in the linked issue, is not a valid option on all os.
