### ISSUE TITLE
Matches at the end of long lines are not visible.

### ISSUE THREAD

**Issue by adriantrunzo** [girishji/scope.vim#9]
# Problem

When my Vim window is narrower, it's very easy not to see matches at the end of long lines. For example, when using the Files finder:

<img width="725" alt="Screenshot 2024-03-14 at 9 16 28 PM" src="https://github.com/girishji/scope.vim/assets/1218900/faaad1df-592a-425f-8f5c-5dc5f8fceb07">

In this case, "position" is at the very end of these file paths. If I make the window wider and re-run the command you can see the match.

<img width="1211" alt="Screenshot 2024-03-14 at 9 21 46 PM" src="https://github.com/girishji/scope.vim/assets/1218900/627622b5-88d1-4594-a5d4-253d82143880">

# Expected Behavior

At least for finding files, truncating the results from the left so that the matches closest to the filename are always visible.

# Actual Behavior

The text is cut off and I can't see the matching segment.

# Discussion

Following the documentation for configuring the plugin, I tried to enable the `wrap` popup window option as a workaround:

```vim
silent! packadd scope.vim

" I also tried #{ wrap: 1 }
if exists('g:loaded_scope')
  call scope#popup#OptionsSet(#{ wrap: v:true })
endif
```

The above had no effect. If I edit [this line in autoload/scope/popup.vim](https://github.com/girishji/scope.vim/blob/0812795db90ab08a2e8e2b59d98df777962a098e/autoload/scope/popup.vim#L44) to `wrap: 1`, I can see the line wrapping:

<img width="725" alt="Screenshot 2024-03-14 at 9 42 34 PM" src="https://github.com/girishji/scope.vim/assets/1218900/82e91d8e-1a56-45d7-83aa-270bbd93c6ce">

The documentation reads:

> The appearance of the popup window can be customized using `borderchars`,
`borderhighlight`, `highlight`, `scrollbarhighlight`, `thumbhighlight`, and
other `:h popup_create-arguments`. To configure these settings, use
`scope#popup#OptionsSet()`.

Not sure if I did something wrong or if customizing `wrap` is just not supported at the moment. Thanks!

**Comment by girishji** [comment]
Should be fixed now. Try.

**Comment by adriantrunzo** [comment]
Thanks! Setting the line wrapping works for me.
